### ISSUE TITLE
Courier upgrade delay is counted for subsequent couriers

### ISSUE THREAD

**Issue by GIider** [yasp-dota/yasp#911] opened 2016-03-07 14:55 UTC
If you buy a 2nd courier and upgrade it, the yasp analysis will rate your upgrade delay on the second one.

A example match can be found here: https://yasp.co/matches/2203500046/analysis
Void buys a second courier 37 minutes in and upgrades it, receiving an F in courier upgrade delay (2067 seconds vs 20).

I think yasp should ignore courier upgrades after the first.

**Comment by WTFKr0** [comment] 2016-03-07 14:58
Similar to #813

**Comment by howardchung** [comment] 2016-03-07 17:31
duplicate of #813

**Closed by howardchung** 2016-03-07 17:31 UTC
