### ISSUE TITLE
Friends matches

### ISSUE THREAD

**Issue by evaldobratti** [yasp-dota/yasp#651] opened 2015-09-15 21:24 UTC
I've started to develop a functionality to find matches of a player and it's friends, and helps to track stacks, collect matches of you and your friends, etc. I have already done some job on my own, but doing everything alone it's too hard :(

A sample of this is deployed on http://45.55.183.239/friends/88738111,89224557

where on match page you can track matches of players in it by clicking on it's row
http://45.55.183.239/matches/1794495797 and go to the page above as well.

I'm wondering if you would accept a pull request of this functionality, then I'd would start to work on yasp

**Comment by howardchung** [comment] 2015-09-16 00:22
We actually kind of support this functionality already with the included account id filter.

**Comment by evaldobratti** [comment] 2015-09-16 01:15
Yeah, but I couldn't find a way to get matches that were played with another person, only the winrate and some other statistics

**Comment by howardchung** [comment] 2015-09-16 01:16
player pages are just views over a given query.  So if you visited the matches tab and then set the query you would get back all the matches that fit.

**Comment by evaldobratti** [comment] 2015-09-16 01:47
Ok, now I found it :P

The only thing that is left is the stats of the players in the query, but it the functionality is already done, as you previously sad.

Sorry boring you for this

**Comment by howardchung** [comment] 2015-09-16 02:03
Yeah, we're kind of focused on individual players, so if you wanted the stats of those players you'd have to visit their profiles.  Each profile is designed to be "centric" around that player.

**Comment by evaldobratti** [comment] 2015-09-16 13:51
Yeah, I got that
What I want to implement is a easier way to discover people that I have already played with, just get a match and see if I have already played with a person of that match (yeah, I want to blame them :P )

I got the yasp code yesterday at home, I'll start to develop something and if it fits/work well on yasp, may I open a pull request, ok?

**Comment by howardchung** [comment] 2015-09-16 17:00
Sure, feel free to open a PR.

I've thought about this problem already, though.  The problem is that getting the players that a certain player has played with is a relatively expensive operation.  Doing it for 10 players when we try to load a match page is probably going to be pretty slow.  Then after that we have to pairwise-check every pair on the team to see how often they play with each other, and "guess" the stack based on that.  

I suppose it MIGHT be possible to do this just by checking the players in the match against the currently logged in player.  We currently store a cache of "played with" players for users who have visited their profile.  However we may be moving to a cache of raw matches rather than a cache of aggregations so I don't know if we'll be able to support that in the future.

**Comment by evaldobratti** [comment] 2015-09-16 22:50
It's not really necessary "guess" the stack, the function to show with whom you already played with I think it's enough. On the project that I send you when I opened this topic I do the search ajax based. In a relational database it's not that expensive, it's just a select where checking where every pair with the selected player were on the same match. 

But I never worked on nosql databases, so I don't know how it would work.

Have you ever had a problem with steam guard with your credentials on .env file?
It keeps to deny my connection since my virtual machine it's not authenticated on steam guard. I already logged on steam client, but when I run yasp, steam continuously sends me emails with a new key to autenticate.

**Comment by howardchung** [comment] 2015-09-16 23:11
It probably depends on schema.  We would need to iterate through all of a
player's matches and count the players within I think.

You should disable steam guard with the accounts you use.

**Comment by evaldobratti** [comment] 2015-09-16 23:15
I found that option after I wrote last comment, I'll disable it

I'll try to do some tests

**Comment by howardchung** [comment] 2015-09-27 09:40
I'm the process of a major rewrite #582.

As part of this player_matches will now be a distinct table and thus could probably be queried to find the data you're trying to look for.  It's also SQL so you may be more familiar with it.

Open a new issue if you've got something concrete you'd like to do with that data.

**Closed by howardchung** 2015-09-27 09:40 UTC
