### ISSUE TITLE
Filter games/statics by time

### ISSUE THREAD

**Issue by gortiz** [yasp-dota/yasp#754] opened 2015-11-17 11:04 UTC
Related to #410.

When I try to filter games and statistics on YASP, there is a feature I really miss: filter them by time. Usually I want to check how well (or more usually bad ^_^) did I play with some heroes, but I don't really care about my performance one year ago, I want to know how I played the previous weeks or months. Right now I can only filter by patch, but that is not accurate, as the number of games that fulfill that filter depends on the release date of the given patch

**Comment by howardchung** [comment] 2015-11-17 11:08
duplicate of #750

**Closed by howardchung** 2015-11-17 11:08 UTC

**Comment by gortiz** [comment] 2015-11-17 11:55
lol! I looked for "time filter" to avoid duplicates, sorry ^_^
