### ISSUE TITLE
Improve user-friendliness of account_id inputs

### ISSUE THREAD

**Issue by fuzzyloaf** [yasp-dota/yasp#1119] opened 2016-07-12 23:18 UTC
Would like to see under the peers tab the ability to see player groups.

Example. My peers are James, Paul, Frank. I'd like to see stats for when

Me, Paul, Frank play together.
Me, Frank, James play together.
Me, James, Paul play together.
Me James, Paul and Frank play together.

**Comment by howardchung** [comment] 2016-07-13 02:44
You can actually do this already, and it works on any player page aggregation.  Use the "players included" filter.  You have to enter the account IDs of the players, which is a little inconvenient.

It will also include games where those players are on the opposing team, but unless your skill level is very high or very low, this should not be very many matches.

Example, myself with @albertcui and @nicholashh 
https://yasp.co/players/88367253/matches?included_account_id=102344608&included_account_id=75392401&limit=

**Comment by howardchung** [comment] 2016-07-14 06:20
Closing unless there's some additional functionality you're looking for

**Comment by fuzzyloaf** [comment] 2016-07-14 14:21
I have gotten that to work. It took me awhile to figure out how to get the steam ID's and if it's something I'd regularly like to look at I'd have to store them close by. What I was envisioning is the following:

On the peers tab you can make a separate table under the peers table called something like "Groups" and then it would list any games with player combinations from your peers. So you'd see how many games played with that combination and then what winning %.

If you agree this could be a good feature and want to add it to the list I'd appreciate it.

**Comment by howardchung** [comment] 2016-07-14 16:34
The problem is that there are too many possible combinations.  There are 2^n-1 possibilities, so this becomes impractical with more than 3-4 friends.  Each distinct combination also requires a separate aggregation on the player's matches, so it becomes very expensive to preload all of the combinations.

**Comment by fuzzyloaf** [comment] 2016-07-14 18:09
I appreciate your feedback. It makes sense.

I typically play with just a few friends so I didn't really think about the impact.

What if it just showed some check boxes or some other way to just quickly select 2 or more friends to show the stats for just those friends at the time it's needed.

Or maybe pre populate the ID field with your peers but also allowing manual entries?

Thoughts?

**Comment by howardchung** [comment] 2016-07-15 07:43
Prepopulating (basically making the form more user-friendly) is a possibility.

Actually, we used to have that, but it suffered from a performance problem.  Getting the list of friends required aggregation over a player's matches, which slowed load times.

We might be able to bring it back with the SPA, where it's easier to make additional API calls directly from the page on-demand (only when the user tries to fill the field).

**Comment by fuzzyloaf** [comment] 2016-07-15 18:20
Thanks Howard. Really appreciate your efforts.

**Comment by howardchung** [comment] 2016-08-06 17:43
Moving to UI repo

**Closed by howardchung** 2016-08-06 17:43 UTC
Labels: ui
